import re

# ===== أيقونات =====
icon_client   = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAOmUlEQVR4nO3dS6ycdR3G8d/pBSgFwSBSSkEF6Q2JGzWIRhITNUETdkpiQkLiTjfqRnfGlTExxkRwo8SoMSa48JIACSyMIQqxQEAR0AIBsbTghZZbaUuPiylCoZdzzrwz7/t/n88nmTQpM9M/C/p8Z87wzkJBVS3uqsW+zwDA/Kzq+wD0z/gD5BEA4Yw/QCYBEMz4A+QSAKGMP0A2ARDI+AMgAMIYfwCqBEAU4w/AawRACOMPwBsJgADGH4A3EwAjZ/wBOBYBMGLGH4DjEQAjZfwBOBEBMELGH4CTEQAjY/wBWAoBMCLGH4ClEgAjYfwBWA4BMALGH4DlEgCNM/4ArIQAaJjxB2ClBECjjD8A0xAADTL+AExLADTG+APQBQHQEOMPQFcEQCOMPwBdEgANMP4AdE0ADJzxB2AWBMCAGX8AZkUADJTxB2CWBMAAGX8AZk0ADIzxB2AeBMCAGH8A5kUADITxB2CeBMAAGH8A5k0A9Mz4A9AHAdAj4w9AXwRAT4w/AH0SAD0w/gD0TQDMmfEHYAgEwBwZfwCGQgDMifEHYEgEwBwYfwCGRgDMmPEHYIgEwAwZfwCGSgDMiPEHYMgEwAwYfwCGTgB0zPgD0AIB0CHjD0ArBEBHjD8ALREAHTD+ALRGAEzJ+APQIgEwBeMPQKsEwAoZfwBaJgBWwPgD0DoBsEzGH4AxEADLYPwBGAsBsETGH4AxEQBLYPwBGBsBcBLGH4AxEgAnYPwBGCsBcBzGH4AxEwDHYPwBGDsB8CbGH4AEAuANjD8AKQTAEcYfgCQCoIw/AHniA8D4A5AoOgCMPwCpYgPA+AOQLDIAjD8A6eICwPgDQFgAGH8AmIgJAOMPAK+LCADjDwBHG30AGH8AeKtRB4DxB4BjG20AGH8AOL5RBoDxB4ATG10AGH8AOLlRBYDxB4ClGU0AGH8AWLpRBIDxB4DlaT4AjD8ALF/TAWD8AWBlmg0A4w8AK9dkABh/AJhOcwFg/AFgek0FgPEHgG40EwDGHwC600QAGH8A6NbgA8D4A0D3Bh0Axh8AZmOwAWD8AWB2BhkAxh8AZmtwAWD8AWD2BhUAxh8A5mMwAWD8AWB+BhEAxh8A5qv3ADD+ADB/vQaA8QeAfvQWAMYfAPrTSwAYfwDo19wDwPgDQP/mGgDGHwCGYW4BYPwBYDjmEgDGHwCGZeYBYPwBYHhmGgDGHwCGaWYBYPwBYLhmEgDGHwCGrfMAMP4AMHydBoDxB4A2dBYAxh8A2tFJABh/AGjL1AFg/AGgPVMFgPEHgDatOACMPwC0a0UBYPwBoG3LDgDjDwDtW1YAGH8AGIclB4DxB4DxWFIAGH8AGJeFk93B+EPbXjlQ9cSTVU/vqdrzTNWz/6p6/oWqF16c3A4dOnJ7tWrtmqpTT61ad1rVGeurNpw3uW3cUPXei6vOPKPvfxugKycMAOMP7dm7r+pP91btuK/qwYer/vHPqsOHp3/ehYWqTRurLtta9f7Lq678UNXbz57+eYF+HDcAjD+05a4dVb++peruHZNX9LO2aqFq+9aq666tuuKDs//zgG6tOdZvGn9ox992Vn33xsmr/Xk6vFj1l4eq7rlfAECL3hIAxh/a8ctfV934o/m84gfG5agAMP7Qjpt+VvXjn/d9CqBV///fAI0/tOOW240/MJ1VVcYfWvLUrqrvfL/vUwCtW2X8oS3f+0HVwYN9nwJo3Yq/DhiYvwcfrrr7nr5PAYyBAICG3Pyrvk8AjIUAgEbs31915119nwIYCwEAjbhrR9WBA32fAhiLY14JEBiee+/v/jlXLVSddVbVaadVrV1b9eqhqpf3T95teHl/1aKPCMNoCQBoRFeX+r3iA1Ufv6pq+5aqC86vWr362Pc7eLBqz7NVu/dU7dpdtfOxqr8/VvXo45NAANomAKABhw9XPf7EdM9x+rqqr3+l6qqPLO3+a9dOvv1v08Y3nWWxauejVfc9UHXvA1XrT5/uXEA/FlwHAIZv956qz14/3XN87ctVV3+im/MA7fMhQGjA03ume/wl7zH+wNEEADTgub3TPf5jV3ZzDmA8BAA04IUXp3v89q3dnAMYDwEADZj2U/dnn9XNOYDxEADQgFNPme7xPqkPvJkAgAasXz/d459/vptzAOMhAKABF2w8+X1O5JGd3ZwDGA8BAA1416bJZXtX6rY7ujsLMA4CABqwbl3Vls0rf/xfH6m69fbuzgO0TwBAI674wHSP/84NVb//QzdneaNnnq3693+6f15gtlwKGBqx+5mqa6+fXIt/pRYWqj7zqarrP1/1jnOW99gDB6oef3LypUCPPj657Xys6vkXqr76paprrl75uYD582VA0IgN76z66IenexW/uFj129uqbr2j6qNXTK4QePllVeed+/p9Di9WPfuvyZcPPfpY1c4jY//kU5MvJQLGQQBAQ774hap775/+yoCHDlX97s7JrWryzX9nrJ8M/IsvTf45MG4+AwANOX9D1be/WXXmGd0+78GDVf99rmrvPuMPKQQANOZ926puuqHqyg/1fRKgZX4EAA0679yqb32j6uG/Vf3m1qrf/7Fq376+TwW0xDsA0LBLL6m65tNV132u6sIL+j4N0BLvAEBDXnyp6sGHqv7816oHHqx66JGq/a/0fSqgRQIAGvHDn1b97BfTXQcA4DV+BACNeG6v8Qe6IwAAIJAAAIBAAgAAAvkQILBip5xStfmSqos29X0SYLkEALAkqxaqLrqwatuWqu1bqrZtrrr43VVr/C0CTfKfLnBM555TtW1r1bZLq7ZvrdpyadXp6/o+FdAVAQDU+tMnA7/tyCv77Vuq3nFO36cCZkkAQJg1ayZv3W/fUrX1yNhfdOHkLX4ghwCAkbvg/KNf2V96yeTDe0A2AQAjctbb3jD2Wye/vu3Mvk8FDJEAgEaddmrV5vdO3sbftnky/Bs39H0qoBUCABqxcUPVpz/5+thf/O6q1av7PhXQqoXFXeXrRQAgjEsBA0AgPwKAhuzdV7V3b9+neKtVq6s2bez7FMByCABoyM2/qvrJL/o+xVutX1916819nwJYDj8CAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAItLO6qxb4PAQDMl3cAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQP8DYh6X32kVG10AAAAASUVORK5CYII="    # قطع يسار
icon_assistant = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAOmklEQVR4nO3dS6wedR3H4d/phVIKggGkHAoil96QuEGCSCQxURMwYackJiQk7nSjbnRnXBkTYkwEN0qMEkOCC9AESGBhCFGIXALK1QIBsVBApeVW2tLj4i1SSgvnnPcy85/v8ySTLs47018X7f8z805n5ha210IBEGVuvua6noFureh6AABmz8kfAgAglAjIJgAAgomAXAIAIJwIyCQAABABgQQAAFUlAtIIAAD+TwTkEAAAvI8IyCAAAPgAETB8AgCAwxIBwyYAADgiETBcAgCADyUChkkAAPCRRMDwCAAAFkUEDIsAAGDRRMBwCAAAlkQEDIMAAGDJRED7BAAAyyIC2iYAAFg2EdAuAQDAWERAmwQAAGMTAe0RAABMhAhoiwAAYGJEQDsEAAATJQLaIAAAmDgR0H8CAICpEAH9JgAAmBoR0F8CAICpEgH9JAAAmDoR0D8CAICZEAH9IgAAmBkR0B8CAICZEgH9IAAAmDkR0D0BAEAnREC3BAAAnREB3REAAHRKBHRDAADQOREwewIAgF4QAbMlAADoDREwOwIAgF4RAbMhAADoHREwfQIAgF4SAdMlAADoLREwPQIAgF4TAdMhAADoPREweQIAgCaIgMkSAAA0QwRMjgAAoCkiYDIEAADNEQHjEwAANEkEjEcAANAsEbB8AgCApomA5REAADRPBCydAABgEETA0ggAAAZDBCyeAABgUETA4ggAAAZHBHw0AQDAIImADycAABgsEXBkAgCAQRMBhycAABg8EfBBAgCACCLg/QQAADFEwHsEAABRRMCIAAAgjggQAACESo8AAQBArOQIEAAAREuNAAEAQLzECBAAAFB5ESAAAOCApAgQAABwkJQIEAAAcIiECBAAAHAYQ48AAQAARzDkCBAAAPAhhhoBAgAAPsIQI0AAAMAiDC0CBAAALNKQIkAAAMASDCUCBAAALNEQIkAAAMAytB4BAgAAlqnlCBAAADCGViNAAADAmFqMAAEAABPQWgQIAACYkJYiQAAAwAS1EgECAAAmrIUIEAAAMAV9jwABAABT0ucIEAAAMEV9jQABAABT1scIEAAAMAN9iwABAAAz0qcIEAAAMEN9iQABAAAz1ocIEAAA0IGuI0AAAEBHuowAAQAAHeoqAgQAAHSsiwgQAADQA7OOAAEAAD0xywgQAADQI7OKAAEAAD0ziwgQAADQQ9OOAAEAAD01zQgQAADQY9OKAAEAAD03jQgQAADQgElHgAAAgEZMMgIEAAA0ZFIRIAAAoDGTiAABAAANGjcCBAAANGqcCBAAANCw5UaAAACAxi0nAgQAAAzAUiNAAADAQCwlAgQAAAzIYiNAAADAwCwmAuam/b5hoFtv76l69rmqF3ZU7Xip6uVXql57ver1N0bbvn0HtneqVq+qWrOmau3RVceuq1p/ymibX191zllVxx3b9Z8GWIq5+Zo74s8EAAzLzl1Vf32g6r4Hqx55vOqf/6rav3/8487NVW2Yrzpvc9Vnzq+6+MKqj58w/nGB6TpSBAgAGIh77qu65daqe+8bndFP24q5qq2bq666suqiz07/9wOW73ARsKqLQYDJeXJb1U+vG53tz9L+haq/P1Z1/0MCAPpuYXstHBoBAgAa9vtbqq771WzO+IG2HRoBAgAadf0NVb/+XddTAC05OAL8N0Bo0K13WPyB5Xn33j8BAI15fnvVNT/vegqgZQvba0EAQGN+9ouqvXu7ngJonQCAhjzyeNW993c9BTAEAgAactPNXU8ADIUAgEbs3l119z1dTwEMhQCARtxzX9WePV1PAQyF5wBAIx54aPLHXDFXdfzxVUcfXbV6ddU7+6re2j262vDW7qoFDwqHwRIA0IhJPer3oguqvnhp1dZNVaedWrVy5eE/t3dv1Y6Xq17cUbX9xaptT1f94+mqp54ZBQLQNgEADdi/v+qZZ8c7xjFrq37w3apLP7+4z69ePXr734b5Q2ZZqNr2VNWDD1c98HDVumPGmwvohrcBQgNe3FH1tavHO8b3v1N12ZcmMw/QPjcBQgNe2DHe/md/yuIPvJ8AgAa8unO8/b9w8WTmAIZDAEADXn9jvP23bp7MHMBwCABowLh33Z9w/GTmAIZDAEAD1hw13v7u1AcOJQCgAevWjbf/a69NZg5gOAQANOC0+Y/+zId5Yttk5gCGQwBAAz65YfTY3uW6/c7JzQIMgwCABqxdW7Vp4/L3f/SJqtvumNw8QPsEADTiogvG2/+aa6vu+vNkZjnYSy9X/fs/kz8uMF0eBQyNePGlqiuvHj2Lf7nm5qq++pWqq79RddKJS9t3z56qZ54bvRToqWdG27anq157vep736664rLlzwXMnpcBQSPWf6Lqks+Ndxa/sFD1x9urbruz6pKLRk8IPP+8qlNOfu8z+xeqXn5l9PKhp56u2nZgsX/u+dFLiYBhEADQkG99s+qBh8Z/MuC+fVV/unu0VY3e/HfsutEC/8abo58Dw+YeAGjIqeurfvKjquOOnexx9+6t+u+rVTt3WfwhhQCAxnx6S9X111ZdfGHXkwAt8xUANOiUk6t+/MOqx5+s+sNtVXf9pWrXrq6nAlriCgA07Nyzq664vOqqr1edflrX0wAtcQUAGvLGm1WPPFb1t0erHn6k6rEnqna/3fVUQIsEADTil7+tuuHG8Z4DAPAuXwFAI17dafEHJkcAAEAgAQAAgQQAAARyEyCwbEcdVbXx7KozNnQ9CbBUAgBYlBVzVWecXrVlU9XWTVVbNladdWbVKv+KQJP81QUO6+QTq7ZsrtpybtXWzVWbzq06Zm3XUwGTIgCAWnfMaIHfcuDMfuumqpNO7HoqYJoEAIRZtWp06X7rpqrNBxb7M04fXeIHcggAGLjTTn3/mf25Z49u3gOyCQAYkOM/dtBiv3n068eO63oqoI8EADTq6DVVG88ZXcbfsnG08M+v73oqoBUCABoxv77q8i+/t9ifdWbVypVdTwW0am5he3m9CACE8ShgAAjkKwBoyM5dVTt3dj3FB61YWbVhvuspgKUQANCQm26u+s2NXU/xQevWVd12U9dTAEvhKwAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAg0NzC9lroeggAYLZcAQCAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAL9D7o8lb/9rL/hAAAAAElFTkSuQmCC"    # قطع يمين

def fix_dashboard(path, icon_b64, label):
    print(f"\n{'='*40}")
    print(f"🔧 {label}")
    print(f"{'='*40}")
    
    with open(path, "r", encoding="utf-8") as f:
        html = f.read()
    
    changes = 0
    
    def rep(old, new):
        nonlocal changes, html
        c = html.count(old)
        if c:
            html = html.replace(old, new)
            changes += c
            print(f"  ✅ غيّر: {old[:40]} ({c}x)")
        else:
            print(f"  ⚪ مش موجود: {old[:40]}")
    
    # 1. body background = أصفر (الـ gradient)
    rep('#5C4A00 0%,#7A6200 50%,#5C4A00 100%', '#FFE600 0%,#E6CA00 50%,#FFE600 100%')
    rep('#1B5E20 0%,#2E7D32 50%,#1B5E20 100%', '#FFE600 0%,#E6CA00 50%,#FFE600 100%')
    
    # 2. theme-color = أصفر
    rep('content="#5C4A00"', 'content="#FFE600"')
    rep('content="#1B5E20"', 'content="#FFE600"')
    rep('content="#2E7D32"', 'content="#FFE600"')
    
    # 3. CSS variables = navy (للكروت)
    rep('--dark:#5C4A00;', '--dark:#0D1B4B;')
    rep('--dark2:#7A6200;', '--dark2:#1E2761;')
    rep('--dark:#1B5E20;', '--dark:#0D1B4B;')
    rep('--dark2:#2E7D32;', '--dark2:#1E2761;')
    
    # 4. header background = navy
    rep('background:rgba(92,74,0,0.85)',   'background:rgba(13,27,75,0.95)')
    rep('background:rgba(92,74,0,0.95)',   'background:rgba(13,27,75,0.95)')
    rep('background:rgba(27,94,32,0.85)',  'background:rgba(13,27,75,0.95)')
    rep('background:rgba(27,94,32,0.95)',  'background:rgba(13,27,75,0.95)')
    rep('background:rgba(46,125,50,0.85)', 'background:rgba(13,27,75,0.95)')
    rep('background:rgba(46,125,50,0.95)', 'background:rgba(13,27,75,0.95)')
    
    # 5. modal background = navy
    rep('background:#7A6200;', 'background:#1E2761;')
    rep('background:#1B5E20;', 'background:#1E2761;')
    rep('background:#2E7D32;', 'background:#1E2761;')
    
    # 6. أي لون قديم متبقي
    rep('#5C4A00', '#0D1B4B')
    rep('#7A6200', '#1E2761')
    rep('#1B5E20', '#0D1B4B')
    rep('#2E7D32', '#1E2761')
    
    # 7. الأيقونة
    old_count = len(re.findall(r'data:image/png;base64,[A-Za-z0-9+/=]+', html))
    html = re.sub(r'data:image/png;base64,[A-Za-z0-9+/=]+', f'data:image/png;base64,{icon_b64}', html)
    print(f"  ✅ أيقونات: {old_count}")
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"  ✅ تم الحفظ! ({changes} تغيير)")

# تشغيل على الملفين
fix_dashboard(
    r"C:\Users\karim\Documents\GitHub\amin-alsir-test\amin_alsir_client_dashboard.html",
    icon_client,
    "داشبورد العميل (قطع يسار)"
)

fix_dashboard(
    r"C:\Users\karim\Documents\GitHub\amin-alsir-test\amin_alsir_assistant_dashboard.html",
    icon_assistant,
    "داشبورد المساعد (قطع يمين)"
)

print("\n\n🎉 انتهى! الملفين جاهزين للـ push")
